name: Linux aarch64build c1

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  boinc_ref: 82d0a3731c743884b6e7a25d68c6558eca691635
  gwnum_ver: "v3107b01"
  gwnum_ver_major: "31"
  gwnum_ver_minor: "07"

jobs:
  boinc-linux-aarch64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Cache BOINC libs
        id: cache-boinc-linux-aarch64
        uses: actions/cache@v5
        with:
          path: |
            boinc/*.*
            boinc/api
            boinc/lib
          key: boinc-${{ runner.os }}-${{ env.boinc_ref }}-linux-aarch64-clang

      - name: Checkout boinc
        if: steps.cache-boinc-linux-aarch64.outputs.cache-hit != 'true'
        uses: actions/checkout@v5
        with:
          repository: BOINC/boinc
          ref: ${{ env.boinc_ref }}
          path: boinc

      - name: Install deps
        if: steps.cache-boinc-linux-aarch64.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            autoconf \
            automake \
            libtool \
            pkg-config \
            m4

      - name: Build boinc
        if: steps.cache-boinc-linux-aarch64.outputs.cache-hit != 'true'
        env:
          CC: clang
          CXX: clang++
        run: |
          cd ./boinc/
          ./_autosetup
          ./configure \
            --disable-server \
            --disable-client \
            --disable-manager \
            --enable-libraries \
            --enable-static \
            --disable-shared
          make -j$(nproc)

  gwnum:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Cache gwnum.a libs
        id: cache-gwnum-linux-aarch64
        uses: actions/cache@v5
        with:
          path: |
            gwnum_c1/gwnum.a
          key: gwmum-${{ runner.os }}-${{ env.gwnum_ver }}-linux-aarch64-clang

      - name: Install deps
        if: steps.cache-gwnum-linux-aarch64.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build

      - name: Download gwnum c1
        if: steps.cache-gwnum-linux-aarch64.outputs.cache-hit != 'true'
        run: git clone https://github.com/sam8641/gwnum_c1.git

      - name: Build gwnum c1
        if: steps.cache-gwnum-linux-aarch64.outputs.cache-hit != 'true'
        env:
          CC: clang
          CXX: clang++
        run: |
          cd gwnum_c1
          cmake -G Ninja -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++
          cmake --build build -j 4
          mv build/libgwnum_c1_lib.a gwnum.a

  linux-aarch64:
    needs: [boinc-linux-aarch64, gwnum]
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            libgmp-dev

      - name: Use cached BOINC libs
        id: cache-boinc
        uses: actions/cache@v5
        with:
          path: |
            boinc/*.*
            boinc/api
            boinc/lib
          key: boinc-${{ runner.os }}-${{ env.boinc_ref }}-linux-aarch64-clang
          fail-on-cache-miss: true

      - name: Use cached gwnum
        id: cache-gwnum
        uses: actions/cache@v5
        with:
          path: |
            gwnum_c1/gwnum.a
          key: gwmum-${{ runner.os }}-${{ env.gwnum_ver }}-linux-aarch64-clang
          fail-on-cache-miss: true

      - name: Checkout prst
        uses: actions/checkout@v5
        with:
          submodules: true
          path: prst

      - name: Copy gwnum
        run: |
          cp gwnum_c1/gwnum.a prst/framework/gwnum/linux64/

      - name: Make
        env:
          CC: clang
          CXX: clang++
        run: |
          cd prst/src/linux-aarch64
          make -j$(nproc)

      - name: Make (boinc)
        env:
          CC: clang
          CXX: clang++
        run: |
          cd prst/src/linux-aarch64
          make -f Makefile.boinc \
            BOINC_DIR=$GITHUB_WORKSPACE/boinc \
            -j$(nproc)

      - name: Smoke test
        run: |
          cd prst/src/linux-aarch64
          file prst | grep -q 'statically linked'
          file prst_boinc | grep -q 'statically linked'
          ./prst -v
          ./prst_boinc -v
          ./prst -log info "3*2^534+1" | tee proth.log
          grep -q 'is prime!' proth.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: linux-aarch64_bins
          path: |
            prst/src/linux-aarch64/prst
            prst/src/linux-aarch64/prst_boinc
            gwnum_c1/gwnum.a